### ISSUE TITLE
Documentation to Use SPARTA

### ISSUE THREAD

**Issue by ashispapu** [facebookincubator/SPARTA#3]
Hi Team,

Thank you for releasing SPARTA. I am trying to explore  different functionalities and APIs of SPARTA.However I am not able to find any document which explains the usage of SPARTA. Please let me know if there is any detailed document and examples to use SPARTA for different applications.
@int3 @facebook-github-bot , Any help is highly appreciated.
Thank you.
Ashis

**Comment by arnaudvenet** [comment]
All header files contain documentation and code snippets that explain how to use the various data structures. The unit test [MonotonicFixpointIteratorTest](https://github.com/facebookincubator/SPARTA/blob/master/test/MonotonicFixpointIteratorTest.cpp) shows how to set up a complete analysis (live variables) for a toy language.

Since SPARTA is programming-language independent, the documentation doesn't go into all the details of analyzing a real programming language. The Android bytecode optimizer [Redex](https://github.com/facebook/redex) makes extensive use of SPARTA for its optimization passes and I would recommend browsing the code base for more realistic use cases. The [interprocedural constant propagation](https://github.com/facebook/redex/tree/master/service/constant-propagation) would be a great example: it uses nearly every single data structure in SPARTA and it's also very well documented.
